name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ release ]   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    
  deploy-pre:
    runs-on: ubuntu-latest
    environment:
      name: pre
      url: 'http://fiapdevops.herokuapp.com/agl'
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: AkhileshNS/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        heroku_app_name: ${{secrets.HEROKU_APP}}
